# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.3
env:
  global:
    - WORKSPACE=SideMenuController.xcworkspace
    - FRAMEWORK_NAME=SideMenuController
    - PROJECT=SideMenuController.xcodeproj
    - SCHEME=SideMenuController
    - SDK=iphonesimulator9.3
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
script:
- set -o pipefail
- xcodebuild test -workspace $WORKSPACE -scheme $SCHEME -sdk $SDK ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
